spring:
    config:
        import: env.properties
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                    naver:
                        client-id: ${NAVER_CLIENT_ID}
                        client-secret: ${NAVER_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        redirect-uri: ${baseUrl}/login/oauth2/code/naver
                        client-name: Naver
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

                        
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        driver-class-name: org.h2.Driver
        url: 'jdbc:h2:mem:test'
        username: sa
        password: